#!/usr/bin/env python3

"""
Salmonella Genomic Clustering and Threshold Optimization via FastANI.

This script parses an all-vs-all Average Nucleotide Identity (ANI) matrix 
generated by FastANI, reconstructs it into a symmetric format, and performs 
hierarchical clustering. It includes a hyperparameter tuning step that 
evaluates different distance thresholds using Silhouette Scores to determine 
the optimal number of clusters.

Methodology:
    * Distance Metric: Euclidean distance calculated from ANI values.
    * Linkage Method: Average Linkage (UPGMA), consistent with standard 
      microbial genomic studies.
    * Validation: Silhouette Analysis to measure cluster cohesion and separation.

Input:
    * A .matrix file from FastANI (lower-triangular or sparse format).
    
Output:
    * A printed DataFrame of the symmetric ANI matrix.
    * A dual-axis plot (PNG) showing the relationship between distance 
      thresholds, cluster counts, and Silhouette Scores.

Dependencies:
    * pandas, numpy: Data manipulation.
    * matplotlib, seaborn: Visualization.
    * scipy: Hierarchical clustering (linkage, fcluster).
    * sklearn: Clustering validation metrics.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, fcluster, dendrogram
from sklearn.metrics import silhouette_score

# --- Configuration ---
input_file = "/home/senekowitsch/Thesis/QC/06_pairwise_ANI/results/fastANI_all_vs_all_output.txt.matrix"
silhouette_score_plt = "results/salmonella_ani_silhouette.png"

# --- 1. Custom Parser for FastANI Matrix ---
# We cannot use pd.read_csv because of the header line and triangular structure.
with open(input_file, 'r') as f:
    lines = f.readlines()

# Line 1 is the number of genomes [cite: 520]
num_genomes = int(lines[0].strip())
names = []
values = []

# Lines 2+ contain the filename followed by ANI values
for line in lines[1:]:
    parts = line.strip().split('\t')
    # Clean name: remove path and keep filename
    names.append(parts[0].split('/')[-1]) 
    if len(parts) > 1:
        values.append([float(x) for x in parts[1:]])
    else:
        values.append([])

# --- 2. Reconstruct Full Symmetric Matrix ---
# Initialize with 100% identity on the diagonal
matrix_data = np.full((num_genomes, num_genomes), 100.0)

for i in range(num_genomes):
    for j, val in enumerate(values[i]):
        matrix_data[i, j] = val
        matrix_data[j, i] = val # Ensure the matrix is symmetric

# Convert to DataFrame for easier handling in Seaborn
matrix_df = pd.DataFrame(matrix_data, index=names, columns=names)
print(matrix_df)

# --- 3. Hierarchical Clustering (Paper Methodology) ---
# Parameters: Euclidean distance and Average Linkage [cite: 141, 524]
row_linkage = linkage(matrix_df, method='average', metric='euclidean')

# Check the range of merge distances
min_dist = row_linkage[:, 2].min()
max_dist = row_linkage[:, 2].max()
median_dist = np.median(row_linkage[:, 2])

print(f"Distances in tree: Min={min_dist:.2f}, Max={max_dist:.2f}, Median={median_dist:.2f}")

# Define a range of thresholds to test
# Based on tree (check max)
thresholds = np.linspace(0.1, 1.5, 29)
results = []

for t in thresholds:
    labels = fcluster(row_linkage, t=t, criterion='distance')
    n_clusters = len(np.unique(labels))
    
    # Silhouette score requires > 1 cluster and < total samples
    if 1 < n_clusters < num_genomes:
        score = silhouette_score(matrix_df.drop(columns=['cluster'], errors='ignore'), labels)
    else:
        score = np.nan
        
    results.append({'threshold': t, 'n_clusters': n_clusters, 'silhouette': score})

tuning_df = pd.DataFrame(results)
print(tuning_df)

fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot Number of Clusters
ax1.set_xlabel('Distance Threshold')
ax1.set_ylabel('Number of Clusters', color='tab:blue')
ax1.plot(tuning_df['threshold'], tuning_df['n_clusters'], marker='o', color='tab:blue', label='N Clusters')
ax1.tick_params(axis='y', labelcolor='tab:blue')

# Plot Silhouette Score on a second Y-axis
ax2 = ax1.twinx()
ax2.set_ylabel('Silhouette Score', color='tab:red')
ax2.plot(tuning_df['threshold'], tuning_df['silhouette'], marker='s', color='tab:red', label='Silhouette Score')
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title("Cluster Fine-Tuning: Threshold vs. Quality")
plt.grid(True, alpha=0.3)
plt.savefig(silhouette_score_plt, dpi=300, bbox_inches='tight')
plt.show()
