#!/usr/bin/env python3
"""
check_5x_rule.py
Validates whether a manually defined set of genomes satisfies the 5x rule
for selective sweep detection, based on Birky's 4x rule framework.

For a given sweep group and a single sister genome, this script:
  1. Reads a pairwise SNP distance list (output of snp-dists -m)
  2. Computes the average pairwise SNP distance within the sweep group
  3. Computes the average SNP distance from each sweep genome to the sister
  4. Calculates the ratio: avg_sister_SNPs / avg_within_SNPs
  5. Reports whether the ratio meets the 5x threshold
  6. Writes results to a tab-separated output file

The 5x rule (modified from Birky et al. 2005) states that a clade is
consistent with a selective sweep if the mean distance to the nearest
outside genome is at least 5x greater than the mean within-group diversity.
Under neutral coalescent theory, a 4x ratio corresponds to a 95% confidence
that the clade represents an independently evolving lineage rather than a
random sample from a panmictic population.

Usage:
    python3 check_5x_rule.py \\
        --name   "Sweep 1" \\
        --snps   snp_list.tab \\
        --sister out_8790705 \\
        --genomes out_11452375 out_11452785 out_11453035 out_8046645 \\
        --out    results.tsv

Arguments:
    --name      Label for the sweep, used only for display (e.g. "Sweep 1")
    --snps      Path to tab-separated pairwise SNP list: sample1, sample2, distance
                Generated by: snp-dists -m alignment.fasta > snp_list.tab
    --sister    Name of the single sister genome to compare the group against
    --genomes   Space-separated list of genome names in the sweep group
    --out       Path to output file (default: 5x_results.tsv)
                If the file already exists, results are appended as a new row
                so multiple sweeps can be collected in one file by calling
                the script repeatedly with the same --out path

Output:
    Prints a formatted summary to stdout and writes a tab-separated file with
    one row per genome in the sweep group:

    sweep_name | genome | sister | within_mean | sister_mean | ratio | rule_met

    sweep_name  : The --name label passed in
    genome      : Name of each genome in the sweep group
    sister      : Name of the sister genome
    within_mean : Mean pairwise SNP distance within the sweep group
    sister_mean : Mean SNP distance from group members to the sister
    ratio       : sister_mean / within_mean
    rule_met    : Yes or No

Example output file:
    sweep_name  genome          sister      within_mean  sister_mean  ratio   rule_met
    Sweep 1     out_11452375    out_8790705 7.81         630.86       80.78   Yes
    Sweep 1     out_11452785    out_8790705 7.81         630.86       80.78   Yes
    ...

Notes:
    - Self-comparisons (a == b) are excluded from within-group pairs
    - Both pair orientations (A,B) and (B,A) are handled automatically
    - If no valid pairs are found, ratio is reported as N/A
    - Results are appended to the output file if it already exists,
      so the script can be called once per sweep without overwriting previous results
"""

import argparse
import os

# Define the expected command line arguments:
parser = argparse.ArgumentParser()
parser.add_argument("--name",     required=True)                # Name/label of the sweep
parser.add_argument("--snps",     required=True)                # Path to the SNP list file from snp_dists
parser.add_argument("--sister",   required=True)                # Single sister genome name
parser.add_argument("--genomes",  nargs="+", required=True)     # list of genomes in the sweep group, "+" means one or more genomes, space-separated
parser.add_argument("--out",      default="5x_results.tsv")     # output file path, appended to if it already exists
args = parser.parse_args()                                      # reads the command line arguments into the "args" object

group = set(args.genomes) # sets are much faster for membership testing than lists
sister = args.sister      # sister genome name as a string

# Two lists to hold the SNP distances for within-group pairs and group-vs-sister pairs
within_snps = []
sister_snps = []

# Open file and split lines into parts
with open(args.snps) as f:
    for line in f:
        a, b, dist = line.strip().split("\t")
        dist = int(dist)    # convert distance to integer
        a_in = a in group   # check if genome a is in the sweep group
        b_in = b in group   # check if genome b is in the sweep group

        if a_in and b_in and a != b:
            within_snps.append(dist)    # both genomes in the group and not the same, add to within-group SNPs
        elif (a_in and b == sister) or (b_in and a == sister):
            sister_snps.append(dist)    # one genome in the group and the other is the sister, add to sister SNPs

# Calculate the average SNP distance for within-group and sister comparisons, and the ratio
# Handle cases where there are no pairs to avoid division by zero
within_mean = sum(within_snps) / len(within_snps) if within_snps else None
sister_mean = sum(sister_snps) / len(sister_snps) if sister_snps else None
ratio = sister_mean / within_mean if within_mean and sister_mean else None
rule_met = "Yes" if ratio is not None and ratio >= 5 else "No"

# Print the results in a clear format
print(f"{'='*30}")
print(f"Sweep: {args.name}")
print(f"Group size: {len(group)} | Sister: {sister}")
print(f"{'─'*30}")
print(f"Within-group pairs:    {len(within_snps)}")
print(within_snps)
print(f"Avg within-group SNPs: {within_mean:.2f}" if within_mean is not None else "No within-group pairs found.")
print(f"Group vs sister pairs: {len(sister_snps)}")
print(f"Avg SNPs to sister:    {sister_mean:.2f}" if sister_mean is not None else "No group-vs-sister pairs found.")
print(f"{'='*30}")
print(f"Ratio (sister/within): {ratio:.2f}" if ratio is not None else "Ratio: N/A")
print(f"5x rule met: {rule_met}")
print()

# --- Write results to output file ---
# If the file does not exist yet, write the header first.
# If it already exists, append without header so multiple sweeps
# can be collected in one file by calling the script once per sweep.
write_header = not os.path.exists(args.out)

with open(args.out, "a") as out:
    if write_header:
        out.write("sweep_name\tgenome\tsister\twithin_mean\tsister_mean\tratio\trule_met\n")
    for genome in sorted(group):
        ratio_str  = f"{ratio:.2f}"  if ratio        is not None else "N/A"
        within_str = f"{within_mean:.2f}" if within_mean is not None else "N/A"
        sister_str = f"{sister_mean:.2f}" if sister_mean is not None else "N/A"
        out.write(
            f"{args.name}\t{genome}\t{sister}\t"
            f"{within_str}\t{sister_str}\t{ratio_str}\t{rule_met}\n"
        )

print(f"Results written to: {args.out}")